### ISSUE TITLE
Issue Generating Package List with Tuist 4 Project Structure

### ISSUE THREAD

**Issue by ammerzon** [FelixHerrmann/swift-package-list#111]
Hi @FelixHerrmann,

First off, thanks for developing such an incredible package. It's been a game-changer for my projects. Currently, I'm working on integrating it into a new project, structured as follows, with dependencies managed via `Package.swift` that is consumed by [Tuist 4](https://docs.tuist.io/documentation/tuist/project-structure).

```swift
.
├── App
│   ├── App.xcodeproj
│   ├── Project.swift
│   ├── Tests
│   └── iOS
├── Frameworks
│   ├── AppFeature
│   ├── Core
│   ├── DesignSystem
│   └── HomeFeature
├── Package.resolved
├── Package.swift
├── Qualifly-PPL-H.xcworkspace
├── Tuist
│   ├── Config.swift
│   └── ProjectDescriptionHelpers
└── Workspace.swift
```

However, I've encountered an issue when executing `swift-package-list` with the error message:

```sh
> swift-package-list Package.swift                                    
Error: No build directory found in /Developer/Xcode/DerivedData for project Developer/ProjectName/Package.swift
```

Could anyone provide insights or suggestions on how to resolve this error?

**Comment by FelixHerrmann** [comment]
Hey, thanks for the kind words!

In general, when working with Tuist projects you have to communicate that by opening the Project.swift file. To explain the error message: everything SPM related in Tuist is not part of derived data directory, it's (hidden) in the project directory.

From the docs you've send me I assume you can also create a Tuist project within a Swift package; let me try to reproduce that and I'll see what I can do to support that!

**Comment by ammerzon** [comment]
Thanks for the clarification. Maybe this helps in reproducing the issue. When running the `swift-package-list` command in `./App`, I get the following error:

```sh
> pwd
my-project-path/App
> swift-package-list Project.swift
Error: The file “.package.resolved” couldn’t be opened because there is no such file.
make: *** [qualifly-package] Error 1
```

**Comment by FelixHerrmann** [comment]
Unfortunately I was not able to convert a Swift package project to a Tuist one, as described [here](https://docs.tuist.io/documentation/tuist/project-structure#SPM-packages)...

Nonetheless the solution should be simple, somewhere in your projects structure must be the source packages directory (make sure to check hidden directories!); it contains things like `artifacts`, `checkouts`, `repositories` and `workspace-state.json`. Once you found it specify that with the `--custom-source-packages-path` option and it should all work.

Here an example when you fetch SPM dependencies with `swift package resolve` which uses the `.build` directory as source:
```bash
swift-package-list Package.swift --custom-source-packages-path .build
```

Using `tuist install` on a default Tuist project puts it in `Tuist/.build`.

Hope that helps, otherwise I need more instructions on how to reproduce such a project structure on my side!

**Comment by ammerzon** [comment]
Thank you. `swift-package-list Package.swift --custom-source-packages-path .build` works and generates the correct dependency list 😁
