### ISSUE TITLE
Question: What is the swift-package-list looking for?

### ISSUE THREAD

**Issue by notapplicableio** [FelixHerrmann/swift-package-list#60]
I have some packages with license files that are not being included in the output. What strategy is used to discover license content?

**Comment by FelixHerrmann** [comment]
Can you show me one or more examples where it's failing? (Screenshot of the package root directory or url if it's public)
The filename and location are the key factors.

**Comment by notapplicableio** [comment]
I originally noticed it with a private package that wraps a third-party library. (This has a LICENSE.md.)

But, I think the same is happening with:
- https://github.com/kishikawakatsumi/KeychainAccess.git
- https://github.com/MindscapeHQ/raygun4apple.git which uses a LICENCE.md (British/NZ spelling of license)
- https://github.com/okta/okta-oidc-ios

**Comment by FelixHerrmann** [comment]
Thanks, the British spelling is indeed not handled, the other ones should work from a first glance tho, will investigate that!

**Comment by notapplicableio** [comment]
Thanks, Felix. By the way, love this package. I selected it some time ago when it just supported JSON - which wasn't ideal, but I still liked it - but that you've added additional support is truly appreciated. :)

**Comment by FelixHerrmann** [comment]
Thanks for the kind words! And yes, this tool def. evolved compared to what it was at the beginning...

**Comment by FelixHerrmann** [comment]
> I originally noticed it with a private package that wraps a third-party library. (This has a LICENSE.md.)
> 
> But, I think the same is happening with:
> 
> * https://github.com/kishikawakatsumi/KeychainAccess.git
> * https://github.com/MindscapeHQ/raygun4apple.git which uses a LICENCE.md (British/NZ spelling of license)
> * https://github.com/okta/okta-oidc-ios

Ok I did some investigations, I added all of these to a demo project and the only one that fails for me is the British spelling one (which was expected because it's not handled). I will fix that but I cannot investigate the other ones from my side. The checked-out package repositories are located at ~/Library/Developer/Xcode/DerivedData/***your-project***/SourcePackages/checkouts if you want to take a look there, mine looks like this:
<img width="1552" alt="Screenshot 2023-08-03 at 16 29 17" src="https://github.com/FelixHerrmann/swift-package-list/assets/42500484/80868c60-cf8d-4194-ac06-984c7fda66e7">

The logic for the license find is located here: https://github.com/FelixHerrmann/swift-package-list/blob/9531edced86b4077c0d62409b68a3e93c8885fb7/Sources/SwiftPackageListCore/File%20Representations/PackageResolved.swift#L55

**Comment by notapplicableio** [comment]
Thanks, your fix for "licence" works perfectly.

Through some instrumentation I have discovered that the content of "pins" in the Package.resolved file is not the same as the packages I have added. So, in the case above, Keychain is not appearing in there so never gets picked up by swift-package-list.

This is not really your problem anymore, but do you know why this file would be out of sync?

**Comment by FelixHerrmann** [comment]
> Thanks, your fix for "licence" works perfectly.

Awesome, will make a release then!

> NVM: I'm using an xcworkspace! Now it all works! :)

Perfect, good to hear that! If I have to guess, you had an xcodeproj with SPM and converted that to a xcworkspace at some point. As soon as you have the workspace this will maintain the source of truth (Package.resolved) for your packages.
