### ISSUE TITLE
Feature Request: Resolving Package name instead of repository name

### ISSUE THREAD

**Issue by Jonas1893** [FelixHerrmann/swift-package-list#70]
Hi, thank you for maintaining this great tool! 

Looking at the output it seems like that the dependency name from Package.resolved is always the repository name but not the Package name as in the name as defined in the Package.swift file.

As an example see the following output:
```
{
    "license" : "Copyright 2015 Catamorphic, Co.\n\nLicensed under the Apache License, Version 2.0 (the \"License\");\nyou may not use this file except in compliance with the License.\nYou may obtain a copy of the License at\n\n    http:\/\/www.apache.org\/licenses\/LICENSE-2.0\n\nUnless required by applicable law or agreed to in writing, software\ndistributed under the License is distributed on an \"AS IS\" BASIS,\nWITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\nSee the License for the specific language governing permissions and\nlimitations under the License.\n",
    "name" : "ios-client-sdk",
    "repositoryURL" : "https:\/\/github.com\/launchdarkly\/ios-client-sdk",
    "revision" : "89d87b2b492624dab41dc407fd11b18ebb3e90cf",
    "version" : "8.3.1"
  },
```
`name` is defined as ios-client-sdk here.

When looking at the [Package.swift file in the dependencies repo](https://github.com/launchdarkly/ios-client-sdk/blob/0fedd1964fef9e3145526dfb9d13a079f588fbfb/Package.swift) however we see that the Package name is in fact LaunchDarkly. 
I think it would be beneficial if this script could fetch the 'user facing' dependency name resolved from the Package file.

**Comment by FelixHerrmann** [comment]
Thanks for your request! Without doing more investigation I would say this requires some work because we have to bring the manifest into the process and no longer can rely on only the Package.resolved (currently the only thing we use from the source packages directory is the license). I would also not get rid of the current name and add that as an addition parameter. Definitely doable, will take a look when I have some time.

**Comment by Jonas1893** [comment]
> Thanks for your request! Without doing more investigation I would say this requires some work because we have to bring the manifest into the process and no longer can rely on only the Package.resolved (currently the only thing we use from the source packages directory is the license). I would also not get rid of the current name and add that as an addition parameter. Definitely doable, will take a look when I have some time.

I started hacking a bit and I think I have a working solution. I can provide a PR if you are interested and we can work from there if you think that this would be a valuable addition.

**Comment by FelixHerrmann** [comment]
Ok, after some investigation I've found a reliable solution which does not require any source code interaction, it's actually the source that Xcode uses to display them. There are a few things I want to establish with that change:
- change the implementation of `Package.name` to use the name defined in the manifest
- do not interact with Package.swift because it's not guaranteed that the package name is defined statically in the init
- add `Package.identity` to expose the identity concept of SPM (it's very similar to how we have constructed the name in the past)

I've checked your proposed solution and I'm pretty sure it would work as intended, but going the route I've described above should eliminate every edge-case and is aligned with what happens under the hood of SPM.

Changing how name works is a source-breaking change and requires a major version release, I have some more ideas and features I want to add in the near future so you can expect a release of 4.0.0 soon. In the meantime you can pull the unreleased changes I'll contribute now and build it locally to play around with it!

**Comment by martinK-7** [comment]
Hey @FelixHerrmann, thank you for adding this feature! We would like to use it in our environment, could you please provide a rough estimate when there will be a 4.0 release? Thanks 🎉

**Comment by FelixHerrmann** [comment]
Hey @martinK-7, there's one thing missing I want to introduce with the next major version + a migration guide, but that's it; I should be able to address these in the upcoming week(end)s!
