### ISSUE TITLE
Support for Xcode Workspaces

### ISSUE THREAD

**Issue by gaw3** [FelixHerrmann/swift-package-list#8]
I keep getting the following error message:  **No checkouts-path found in your DerivedData-folder**

Xcode 13.2.1, macOS Monterey 12.2

**Comment by FelixHerrmann** [comment]
Hi, thanks for reporting. Do you use the default DerivedData location (you can check that in your Xcode preferences under Locations)? If so, can you provide some more information about the project and maybe send some screenshots (e.g. from the DerivedData's project directory)? That would be really helpful!

**Comment by gaw3** [comment]
Hi,

More info about project: uses Cocoapods and SPM, build for iOS 15.0, I guess I don't know what else you would need to know here...

My DerivedData directory is ~/Library/Developer/Xcode/DerivedData , I am assuming that is the default directory because I have never changed it.

![JUBhd4eSUR40wxaK](https://user-images.githubusercontent.com/7268555/156908595-0339cc4f-e411-421c-b9d0-aa2dc536d104.png)

Sorry for the slow response, I initially responded to the email from github...

**Comment by FelixHerrmann** [comment]
Haha, no problem!

So, there is no .xcworkspace support atm (on what cocoapods projects rely on). I just installed cocoapods tho... I think it's pretty easy to add that!

**Comment by FelixHerrmann** [comment]
Already got it working, I will finish and upload this later today

**Comment by FelixHerrmann** [comment]
Hi, I have just release [1.3.0](https://github.com/FelixHerrmann/swift-package-list/releases/tag/1.3.0), let me know if it works for you know! 

Also, make sure you use the path to the .xcworkspace file instead of .xcodeproj. I've also added a dedicated [run script for workspaces](https://github.com/FelixHerrmann/swift-package-list/tree/master#xcode-workspace-cocoapods) (if you want to use a Run Script Phase, what I highly recommend).
